### PR TITLE
#6055 optimized streaming service response time

### LINKED ISSUE #6055: Retest: Check Speed of the Streaming Service Derived Hourly End Point (in perf env)
The following endpoint call takes more than 30 seconds when using Postman and through the Swagger page.

https://api.epa.gov/easey/dev/streaming-services/emissions/hourly/derived-values?orisCode=3&locationName=1|2|CS0AAN&beginDate=2022-05-31&endDate=2022-07-01

Based on the Hourly Op Data endpoint and the attached test query, this call should take no more than a few seconds.

- Try to determine whether the problem is primarily in querying the database, building the JSON, or transporting JSON.
- Determine whether the query produced by TypeORM is part of the problem.
- Potentially use a view or table function to improve speed.
- Investigate additional indexes to improve speed.

### PR DESCRIPTION
**Pull request by spetros-do**

### CODE REVIEW

**Comment by spetros-do** [comment]
finalQueryTimeUse 6055

**Comment by spetros-do** [comment]
Fixes #6055

**Comment by spetros-do** [comment]
Fixes #6055

**Comment by spetros-do** [comment]
Fixes: [https://github.com/US-EPA-CAMD/easey-ui/issues/6055]

**Review by djw4erg — APPROVED** [review]

**Pull request merged**
